server:
  port: 9004
spring:
  application:
    name: livegoods-details
  profiles:
    active: mongodb,bannerNginx,redis
eureka:
  client:
    service-url:
      defaultZone: http://192.168.89.141:8761/eureka/
  instance:
    prefer-ip-address: true