server:
  port: 9005
spring:
  application:
    name: livegoods-comment
  profiles:
    active: mongodb
eureka:
  client:
    service-url:
      defaultZone: http://192.168.89.141:8761/eureka/
  instance:
    prefer-ip-address: true