server:
  port: 9001
spring:
  application:
    name: livegoods-hot-product
  profiles:
    active: mongodb,bannerNginx
eureka:
  client:
    service-url:
      defaultZone: http://192.168.89.141:8761/eureka/
  instance:
    prefer-ip-address: true